apiVersion: opensearch.bakery.crossplane.io/v1alpha1
kind: OpensearchRole
metadata:
  name: myownrole3
  annotations:
    crossplane.io/external-name: myownrole3
spec:
  forProvider:
    description: "My own role"
    index_permissions:
    - index_patterns:
      - ".kibana_*"
      allowed_actions:
      - "indices_all"
    cluster_permissions:
    - permission_1
    - permission_2
    - permission_3  
  providerConfigRef:
    name: example
